apiVersion: v1
kind: Service
metadata:
  name: autocare-maintenance-service
  namespace: dev
spec:
  selector:
    app: autocare-maintenance-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
